### ISSUE TITLE
[CWM] Create the functional back-end

### ISSUE THREAD

**Issue by rogup** [DigitalCommons/mykomap-monolith#20]
## Description

Create the functional back-end based on the design #14 https://docs.google.com/document/d/1Y2MZ-Q92bhFCit-SoivpriOsxQZIbJop4ewiCqkYRNU/edit

## Subtasks

It probably makes sense to do each of these tasks in its own PR. Write UTs for all the PR's changes within the same PR, rather than leaving them to the end. Try using [BDD](https://github.com/DigitalCommons/land-explorer-front-end/wiki/Automated-Testing) (maybe copy that LX wiki to our codebase docs)

- [x] create the overall app structure, including the classes (e.g. Dataset) and placeholder class instance methods, based on the architecture diagram. #23 
- [x] create simple mock files in the `test/data` directory, based on the file structure in the design and confirmation of what categories we need from Marcel/Colm #24 
- [x] use these mock files to write UTs for the API routes that have already been implemented (i.e. the ones that simply read and return a JSON file) #52 
- [x] implement methods to Dataset class which serve the locations.json, vocabs.json, and individual initiatives <id>.json files #52
- [x] implement method to Dataset class to perform a search using the searchable.json #52

## Acceptance Criteria

- [x] A functional back-end that matches the design
- [x] Full UT coverage of the back-end logic that runs in GitHub CI
- [x] Codebase docs to describe the architecture and any other important details

**Comment by wu-lee** [comment]
Seems mostly okay, I've added some review comments added for PR #23, some of which we already discussed before on a call but I'm adding for the record (not sure of our exact conclusions).

**Comment by ColmDC** [comment]
Assuming this is closable.
