### ISSUE TITLE
[CWM] Update Pop-up Design

### ISSUE THREAD

**Issue by ms0ur1s** [DigitalCommons/mykomap-monolith#22]
## Description

Update the CWM pop-up design making sure to include the following:
- Co-op data sources on the right hand panel
- Data sources could have extra fields, e.g. Coops UK
   - An additional information accordion to be added below any such data source to display additional fields.
   - If possible this should be animated within the design

## Requirements
- Ensure the changes are reflected in both desktop and mobile versions
- The design and layout should should remain consistent with attached design

## Design Reference
![pop-up-design-1](https://github.com/user-attachments/assets/ab096c29-6daf-4abb-98f8-b47ea4ef2f95)

## Tasks

- [x] Create general desktop version of the pop-up
- [x] Create general mobile version of the pop-up
- [x] Create desktop version that includes a data source with extra fields (Co-ops UK used as an example)
- [x] Create a desktop with listed .coop domains below the coop description
- [x] Add animation to the extra fields accordion
- [x] Add additional animation

**Comment by ms0ur1s** [comment]
### Coops UK Desktop Version
[https://xd.adobe.com/view/120a9e57-bdd3-4ed6-9268-f33fe843044b-4759/](https://xd.adobe.com/view/120a9e57-bdd3-4ed6-9268-f33fe843044b-4759/)

This prototype focuses on the pop-up only, and all interaction is centred around this. The pop-up can be opened by clicking on the first item of the results panel or the map marker, and can be closed via map marker or the pop-up close button. The side panel can also be opened or closed to demonstrate the pop-up's position during both states.

**Coops UK Specific** 
The accordion beneath the Coops UK dataset (right panel of the pop-up) can be opened and closed to display Coops UK specific data.

**Comment by ColmDC** [comment]
Hi Marcel. When you say Co-ops UK specific version, what do you mean?

**Comment by ColmDC** [comment]
> When you say Co-ops UK specific version, what do you mean?

This may not be what you meant, but just in case, there shouldn't be anything Co-ops UK specific in the design, or a different Co-ops UK version.

When we include non core fields for a co-op from an individual data source, it would be nice to make those extras fields visible, as in the Co-ops UK example you provide, but I think this is definitely in the nice to haves for Dehli. Given current timeline, I think we should postpone that. The only data source that needs special treatment is DotCoop, as we are using the .coop domains to define merge candidates. 

Q: We need to confirm with DotCoop that they want all the .coop registrations of a co-op listed in the popup.

**Comment by ms0ur1s** [comment]
> Hi Marcel. When you say Co-ops UK specific version, what do you mean?

Morning Colm, the two versions are for illustrative purposes only, to display layouts for co-ops with multiple data sets and Coops UK coops with Coops UK related data.

**Coops UK data - hidden**

![Image](https://github.com/user-attachments/assets/3e234f5b-ca1c-47ba-a2cf-9710a7076a0a)

**Coops UK data - visible**

![Image](https://github.com/user-attachments/assets/b7e2fc0d-ed1d-4124-a38c-a9b98e426797)

**Multiple data sources**

![Image](https://github.com/user-attachments/assets/1006bca5-ca47-4b52-a014-dd2e5a98d5b2)

**Comment by ms0ur1s** [comment]
> This may not be what you meant, but just in case, there shouldn't be anything Co-ops UK specific in the design, or a different Co-ops UK version.

Cool, but showing Coops UK specific data was definitely mentioned in our last conversation as I noted it down, and the solution I proposed was to use an accordion as in the above images, with a working example demonstrated in the Coops UK prototype.

**Comment by ms0ur1s** [comment]
> When we include non core fields for a co-op from an individual data source, it would be nice to make those extras fields visible, as in the Co-ops UK example you provide, but I think this is definitely in the nice to haves for Dehli. Given current timeline, I think we should postpone that. The only data source that may need special treatment is DotCoop, as we are using the .coop domains to define merge candidates.

Pretty sure this is what I've tried to illustrate in the prototypes, I've probably caused the confusion by my wording of the ticket.

**Comment by ms0ur1s** [comment]
**NOTE**
Removed the `Create Coops UK specific mobile version` task as it seemed unnecessary, because a mobile version of the prototype already exists, as does a prototype showing the mechanism for displaying extra Coops UK data.

Will re-add if deemed necessary

![Image](https://github.com/user-attachments/assets/19937063-03d6-4122-b16b-20350ea2afc0)

**Comment by ColmDC** [comment]
>Pretty sure this is what I've tried to illustrate in the prototypes, I've probably caused the confusion by my wording in the ticket. 

it could be a wording confusion. You got time for a quick chat to clarify? @ms0ur1s

**Comment by ColmDC** [comment]
> Q: We need to confirm with DotCoop that they want all the .coop registrations of a co-op listed in the popup.

Dotcoop do still want all registered domains listed.

**Comment by ColmDC** [comment]
> Dotcoop do still want all registered domains listed.
And hyperlinked.

"even if they don't resolve, people will still copy them and find them dead anyway - and we may get feedback that people find it odd that the addresses don't have links. In the future we will probably be doing some educational promotion to encourage users to redirect their defensive domains".

**Comment by ColmDC** [comment]
> Dotcoop do still want all registered domains listed.

In our chat @ms0ur1s we agreed to put the dotcoop domains as the last section on the left panel, as there can be very many. We didn't discuss how to do it in the mobile version. It needs a little thought about the best place to put it. Would we have subscrolling in the white section? Doesn't seem right.

**Comment by ms0ur1s** [comment]
> In our chat [@ms0ur1s](https://github.com/ms0ur1s) we agreed to put the dotcoop domains as the last section on the left panel, as there can be very many. We didn't discuss how to do it in the mobile version. It needs a little thought about the best place to put it. Would we have subscrolling in the white section? Doesn't seem right.

Let me have a think about this one.

**Comment by ms0ur1s** [comment]
### Pop-up with Multiple Domains

**Note:** The content within left hand pane of the pop-up is scrollable via the mouse scroll wheel or draggable via the mouse cursor.
The scrollbar is for illustrative purposes only - to signify scrollable content.

https://xd.adobe.com/view/3ef8c8d0-84bb-480e-bdfe-113d11f1583b-6bab/

**Comment by lin-d-hop** [comment]
@ColmDC Are you now happy to sign of these designs? Is there anything outstanding on this?

**Comment by ColmDC** [comment]
@ms0ur1s was going to comment on the case where there are multiple dotcoop domains on the mobile version, but other than that happy with popup designs.

**Comment by ms0ur1s** [comment]
> @ms0ur1s was going to comment on the case where there are multiple dotcoop domains on the mobile version, but other than that happy with popup designs.

@ColmDC, perhaps we could show the first ten and then have a show more on mobile?

**Comment by ColmDC** [comment]
> @ColmDC, perhaps we could show the first ten and then have a show more on mobile?

Let's do that.
