### ISSUE TITLE
[CWM] Create Pop-up  Component

### ISSUE THREAD

**Issue by ms0ur1s** [DigitalCommons/mykomap-monolith#27]
## Description
Create a Pop-up component based on the designs detailed in [issue #22](https://github.com/DigitalCommons/mykomap-monolith/issues/22). The component should contain all the fields displayed in the aforementioned design, as well as providing for extra fields that a specific data source might contain. The component should be designed for both desktop and mobile layouts and follow the specified structure and functionality:

**Component Breakdown**

- **Outer Pop-up Component -** This will serve as the main container for the pop-up UI.
- **Left Panel -** To contain fields such as: `Co-op Name`, `Primary Activity`, `Description` and `.coop Domains`.
- **Right Panel:** Top section to contain: `Address` and `Website` fields. Bottom section to contain: `Organisational Structure`, `Typology`, and `Data Sources` list.
- **Accordion (share component) -** Should be positioned below any data source that needs to display extra fields.

**Redux Integration**

- Implement a Redux slice to fetch and display data from the backend API via the Redux store. If the API is unavailable, fallback to mock data provided by Rohit.
- The component should be capable of retrieving and rendering the data dynamically.

**Storybook Stories**

- Create Storybook stories for this component to document and test its various states.

## Tasks

- [ ] Develop the outer pop-up component with left and right panels and accordion functionality.
- [ ] Implement Redux slice to fetch and manage data from the backend API or fallback to Rohit's mock data.
- [ ] Add Storybook stories for the component in both desktop and mobile formats.
- [ ] Test the component's responsiveness and ensure it works across various screen sizes.
- [ ] Document the component's functionality, including its interaction with the Redux store.

### Acceptance Criteria

- A fully functional Pop-up component is implemented, following the structure outlined above.
- Desktop and mobile views are both implemented and match the provided designs.
- Redux slice is integrated for API data fetching and mock data fallback.
- Storybook stories are added for the component, covering different states (e.g., no data, loading state, data present).

**Comment by ms0ur1s** [comment]
### Desktop Version - General
[https://xd.adobe.com/view/cd4c3f0e-21ad-49ad-9670-12136cacd8ee-981f/](https://xd.adobe.com/view/cd4c3f0e-21ad-49ad-9670-12136cacd8ee-981f/)

### Desktop Version - Data Source with Extra Fields
[https://xd.adobe.com/view/120a9e57-bdd3-4ed6-9268-f33fe843044b-4759/](https://xd.adobe.com/view/120a9e57-bdd3-4ed6-9268-f33fe843044b-4759/)

### Desktop Version -  Multiple Domains
https://xd.adobe.com/view/3ef8c8d0-84bb-480e-bdfe-113d11f1583b-6bab/

### Mobile Version
[https://xd.adobe.com/view/f51ee4af-db90-4bda-9806-d10c7d7d0f36-a04d/](https://xd.adobe.com/view/f51ee4af-db90-4bda-9806-d10c7d7d0f36-a04d/)

**Comment by ms0ur1s** [comment]
@ColmDC and @lin-d-hop is the issue I've created ok?

**Comment by ms0ur1s** [comment]
Working on this issue until [PR 38](https://github.com/DigitalCommons/mykomap-monolith/pull/38) is merged into main and I can merge main back into branch [272-integrate-main-and-results-panels](https://github.com/DigitalCommons/mykomap-monolith/tree/272-integrate-main-and-results-panels) (perhaps this is a rebase).

**Comment by rogup** [comment]
@ms0ur1s what's the purpose of the [272-integrate-main-and-results-panels](https://github.com/DigitalCommons/mykomap-monolith/tree/272-integrate-main-and-results-panels) branch? It looks like it doesn't have any commits ahead of main

**Comment by ms0ur1s** [comment]
> @ms0ur1s what's the purpose of the [272-integrate-main-and-results-panels](https://github.com/DigitalCommons/mykomap-monolith/tree/272-integrate-main-and-results-panels) branch? It looks like it doesn't have any commits ahead of main

@rogup, sorry man I created this branch before I realised I needed the results panel stuff merged in before I could started it. I could rebase this branch or it might be easier just to start a new one of main now that PR38's merged in.

**Comment by rogup** [comment]
@ms0ur1s I've given it a quick review and it looks good so far. Is the PR finished, or is there more to do?

**Comment by ms0ur1s** [comment]
@rogup, might be a bit or refactoring needed to iron out the kinks in the mobile version (though the mobile version is working). If I haven't updated the PR by the time you're online, do you mind merging it in and I'll stash any further changes and re-instate then in new branch?

**Comment by ms0ur1s** [comment]
@rogup, still in the process of switching this over to use a different MUI component. So you might as well merge this pop-up so that at least there's something there.

**Comment by ms0ur1s** [comment]
@rogup, nice one. Thanks man

**Comment by ColmDC** [comment]
We could create tickets for outstanding documentation and accordian feature, then close.

Any further tweaks relating to scrolling can be new tickets too.

**Comment by ColmDC** [comment]
Nothing more to do on this for Delhi, but moving back into backlog for missing features.

**Comment by lin-d-hop** [comment]
I'm going to close this so we can add enhancement tickets as we are able to prioritise the missing features
