### ISSUE TITLE
[CWM] Integrate CWM into new CWM Website.

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap-monolith#39]
## Description
The CWM will sit in a dedicated page on a new website that is being designed and developed by a third party. The developer needs to know how best to do that.

## Tasks
- [ ] Meet with website developer and identify best way for map to be integrated
- [ ] Provide developer with test url and any other config option required
- [ ] Test responsive performance of map on website
 
## Acceptance Criteria
- The CWM works well on the dedicated CWM website.
