### ISSUE TITLE
[CWM]  Critical mobile UX bugs

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/mykomap-monolith#66]
## Descriptions

In initial mobile testing a number of critical UX issues have come up. These all need fixing.

- [x] Directory, Search and results don't scroll up quite far enough, leaving some content behind the nav
- [x] Pop-up doesn't fit on the screen well, resulting in weird behaviour and a difficulty to view it, particularly on smaller screens
- [x] Add apply filter button and don't open the results panel until this is clicked. The UX on this needs to be clear ie dont make it so you ahve to scroll to see the button.
- [x] Search results not closing when result is clicked (doing this in #64)

## Acceptance Criteria

The above issues are fixed and deployed.

**Comment by ms0ur1s** [comment]
**Task 1:** Added 80px padding to the bottom on the content panel (height of the nav), This bug only appears on my phone and I can't recreate it on my machine using dev tools or the browser plugin I have, so it needs live testing.

**Comment by rogup** [comment]
@ms0ur1s I'll take task 4 and do it as part of my work on #64

**Comment by lin-d-hop** [comment]
Guys! Impressive!
@rogup @ms0ur1s

**Comment by lin-d-hop** [comment]
Can I confirm this has been deployed? Still seeing these issues on my phone :(

**Comment by ms0ur1s** [comment]
> @ms0ur1s I'll take task 4 and do it as part of my work on #64

Thanks man ❤

**Comment by rogup** [comment]
> Can I confirm this has been deployed? Still seeing these issues on my phone :(

Yes, deployed. I'm seeing the changes live - mabybe some browser caching on your end?

**Comment by ms0ur1s** [comment]
### Andriod and IOS positional difference for reference

### Android
![Image](https://github.com/user-attachments/assets/d7670c5b-f4eb-4b96-906c-73487de93cbd)

### IOS
![Image](https://github.com/user-attachments/assets/553edb81-7ce7-411d-8baa-de476caf72ad)

**Comment by ms0ur1s** [comment]
### [PR for the apply filters box positioning bug](https://github.com/DigitalCommons/mykomap-monolith/pull/88)

**Comment by rogup** [comment]
@ColmDC I can't repro this. Maybe it was due to the confusion of the earlier deploy not having updated code. Is it still happening for you, and in what location on the map?

**Comment by ColmDC** [comment]
I'm still seeing it on deploy-2024-11-19-41-g2e5b07b.

![SmallScreen](https://github.com/user-attachments/assets/9d418605-1945-4ecd-b988-36aa60694852)

**Comment by ColmDC** [comment]
>Popups behaving worse on my mobile now. 

I take back statement about behaving worse. There are so many cases. So don't consider this a regression. I think making it possilbe for the user to pan to bring the popup into full view themselves will mean they can always see the data. 

In element I made the suggestion 

"I'm wondering if we can disable the popup disappearing when panning, as when it does clip, the user can at least manually move the popup into view?"

But I know that behaviour was introduced to solve https://github.com/DigitalCommons/mykomap-monolith/issues/78

Rohit suggested then that "Maybe it could temporarily be hidden whilst the map is being panned and then be reshown". This might work as long as it didn't then attempt to recentre once enabled again.

**Comment by ColmDC** [comment]
https://github.com/DigitalCommons/mykomap-monolith/issues/78#issuecomment-2514276741
